# Generated by Django 4.2.4 on 2023-09-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsite', '0003_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank='False', max_length=10),
        ),
        migrations.CreateModel(
            name='Trenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
                ('company', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, to='fsite.company')),
            ],
        ),
    ]
