# Generated by Django 4.2.4 on 2023-09-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsite', '0004_company_title_trenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('company', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, to='fsite.company')),
            ],
        ),
    ]
