# Generated by Django 4.2.4 on 2023-09-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsite', '0005_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='title',
            field=models.CharField(blank='False', max_length=15),
        ),
    ]
