# Generated by Django 4.2.4 on 2023-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsite', '0006_socials_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='False', max_length=15)),
                ('blog_title', models.CharField(blank='False', max_length=40)),
                ('blog_text', models.TextField(blank='False')),
                ('blog_img', models.ImageField(upload_to='images/')),
                ('blog_url', models.URLField(blank='False')),
                ('blog_read_time', models.CharField(blank='False', max_length=20)),
            ],
        ),
    ]
